### ISSUE TITLE
Update PhantomJS to 2.0 

### ISSUE THREAD

**Issue by zckrs** [karma-runner/karma-phantomjs-launcher#64] opened 2015-03-17 09:25 UTC
Can you update PhantomJS to the latest stable release ? http://phantomjs.org/release-2.0.html 

https://github.com/Swiip/generator-gulp-angular/pull/405

**Comment by tplorts** [comment] 2015-03-19 15:46
:+1:

**Comment by tplorts** [comment] 2015-03-19 15:50
duplicate of #56 - note in there about the hold up

**Comment by maksimr** [comment] 2015-05-15 08:08
Close as duplicate

**Closed by maksimr** 2015-05-15 08:08 UTC
