### ISSUE TITLE
Can't load PhantomJS, tried to create a capture at boot

### ISSUE THREAD

**Issue by arnaudlamy** [karma-runner/karma-phantomjs-launcher#52] opened 2015-01-07 13:52 UTC
When I started karma here's what I have:

```sh
INFO [launcher]: Starting browser PhantomJS
INFO [PhantomJS 1.9.8 (Linux)]: Connected on socket K_OSnmGdWVL6vX8zpTq5 with id 86692022
WARN [launcher]: PhantomJS have not captured in 60000 ms, killing.
INFO [launcher]: Trying to start PhantomJS again (1/2).
```

If I look at my processes it seems to capture a page : 

```sh
tests/node_modules/karma-phantomjs-launcher/node_modules/phantomjs/lib/phantom/bin/phantomjs /tmp/karma-15286258/capture.js
```
Any idea what's happening here?
Version:

Npm: 1.4.21
Node: 0.10.25
PhantomJS 1.9.8
Karma v0.12.31

**Comment by titocr** [comment] 2015-01-15 08:05
I was seeing a similar thing on my mac. Finally, noticed that the browser was opening up to www.localhost.com. Commenting out the "::1" from my hosts file solved it for me. Don't know if it's the same issue, but I didn't see it connected to the "...have not captured...." error anywhere.

**Comment by dutscher** [comment] 2015-01-15 18:31
which version of phantomjs-launcher do you have in your package.json?
i got on my windows7:
```
INFO [karma]: Karma v0.12.31 server started at http://localhost:9876/
INFO [launcher]: Starting browser PhantomJS
ERROR [launcher]: Cannot start PhantomJS
```
Node: v0.10.35
PhantomJs: 1.9.8
Karma: v0.12.31

on npm install:
The socket.io dependecie makes hazzle, i got an error if don't have installed the visiual studio. 
With visiual studio i got this warning: 
```
C:\www\cameoJSClient\node_modules\karma\node_modules\socket.io\node_modules\sock
bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
Building the projects in this solution one at a time. To enable parallel build,
  bufferutil.cc
C:\www\cameoJSClient\node_modules\karma\node_modules\socket.io\node_modules\sock
itializing' : conversion from 'size_t' to 'int', possible loss of data [C:\www\c
-client\node_modules\ws\build\bufferutil.vcxproj]
C:\www\cameoJSClient\node_modules\karma\node_modules\socket.io\node_modules\sock
itializing' : conversion from 'size_t' to 'int', possible loss of data [C:\www\c
-client\node_modules\ws\build\bufferutil.vcxproj]
C:\Users\dutscher\.node-gyp\0.10.35\deps\v8\include\v8.h(179): warning C4506: no
::Object>::New(v8::Handle<v8::Object>)' [C:\www\cameoJSClient\node_modules\karma
ufferutil.vcxproj]
     Creating library C:\www\cameoJSClient\node_modules\karma\node_modules\socke
  ib and object C:\www\cameoJSClient\node_modules\karma\node_modules\socket.io\n
  Generating code
  Finished generating code
  bufferutil.vcxproj -> C:\www\cameoJSClient\node_modules\karma\node_modules\soc
  l.node

  validation.cc
C:\www\cameoJSClient\node_modules\karma\node_modules\socket.io\node_modules\sock
itializing' : conversion from 'size_t' to 'int', possible loss of data [C:\www\c
-client\node_modules\ws\build\validation.vcxproj]
C:\www\cameoJSClient\node_modules\karma\node_modules\socket.io\node_modules\sock
itializing' : conversion from 'size_t' to 'int', possible loss of data [C:\www\c
-client\node_modules\ws\build\validation.vcxproj]
C:\Users\dutscher\.node-gyp\0.10.35\deps\v8\include\v8.h(179): warning C4506: no
::Object>::New(v8::Handle<v8::Object>)' [C:\www\cameoJSClient\node_modules\karma
alidation.vcxproj]
     Creating library C:\www\cameoJSClient\node_modules\karma\node_modules\socke
  ib and object C:\www\cameoJSClient\node_modules\karma\node_modules\socket.io\n
  Generating code
  Finished generating code
  validation.vcxproj -> C:\www\cameoJSClient\node_modules\karma\node_modules\soc
  n.node
```
sorry but windows doesn't put out the full log...
can anybody help me? karma and chrome or firefox works.

**Comment by svalchinov** [comment] 2015-06-01 15:28
@titocr 

That fixed it for me, thanks!!!

**Comment by Dignifiedquire** [comment] 2015-06-01 16:14
Looks like the issue is with being able to compile native addons on windows (i.e. needing visual studio) 
Closing this as there is not much we can do from our side to make any different. Feel free to open a new issue if you think there is something that we can do.

**Closed by Dignifiedquire** 2015-06-01 16:14 UTC
Labels: support
