### ISSUE TITLE
"Cannot find module 'phantomjs-prebuilt'" for latest version

### ISSUE THREAD

**Issue by johannesjo** [karma-runner/karma-phantomjs-launcher#104] opened 2016-02-17 01:15 UTC
Using the latest versions for karma, phantomjs and the karma-phantomjs-launcher I get the following errors:
```
[01:12:25] Starting 'testSingle'...
17 02 2016 01:12:25.607:WARN [plugin]: Error during loading "karma-phantomjs-launcher" plugin:
  Cannot find module 'phantomjs-prebuilt'
17 02 2016 01:12:25.665:WARN [karma]: Port 9876 in use
17 02 2016 01:12:25.665:INFO [karma]: Karma v0.13.21 server started at http://localhost:9877/
17 02 2016 01:12:25.666:WARN [launcher]: Can not load "PhantomJS", it is not registered!
  Perhaps you are missing some plugin?
```
And then it is stuck until I open the karma url inside a browser then it runs the tests but still doesn't kill the task though.

**Comment by marlun78** [comment] 2016-02-17 13:44
I get something similar: 
```
[14:38:34] Starting 'test'...
17 02 2016 14:38:34.684:WARN [plugin]: Error during loading "/Users/xxx/xxx/xxx/xxx/node_modules/karma-phantomjs-launcher" plugin:
  Cannot find module 'phantomjs-prebuilt'
[14:38:34] 'test' errored after 72 ms
[14:38:34] Error: Cannot find module 'jasmine-core'
```
Node v5.1.0
NPM: v3.3.12

@johannesjo What version of NPM are you running?

**Comment by GenYDeveloper** [comment] 2016-02-17 14:16
I believe that the phantomjs package was renamed to phantomjs-prebuilt as of version 2.1.4.

**Comment by marlun78** [comment] 2016-02-17 14:19
If I add `"phantomjs-prebuilt": "2.1.4"` to my package.json it woks. But this is not correct.

**Comment by dignifiedquire** [comment] 2016-02-17 14:31
This is correct, you need `phantomjs-prebuilt` to be installed, as it is a peer dependency and this package relies on it since version 1.0

**Comment by marlun78** [comment] 2016-02-17 14:55
Yes @dignifiedquire, you’re right.
>_NOTE: npm versions 1 and 2 will automatically install peerDependencies if they are not explicitly depended upon higher in the dependency tree. In the next major version of npm (npm@3), this will no longer be the case. You will receive a warning that the peerDependency is not installed instead._

From [NPM docs on peerDependencies](https://docs.npmjs.com/files/package.json#peerdependencies)

**Comment by johannesjo** [comment] 2016-02-17 17:31
I can confirm that it works with `phantmjs-prebuilt`

**Comment by chovy** [comment] 2016-03-29 21:12
Still getting this error:

```
$ karma start
29 03 2016 14:12:03.509:WARN [plugin]: Error during loading "/Users/username/.nvm/versions/node/v5.7.1/lib/node_modules/karma-phantomjs-launcher" plugin:
  Cannot find module 'phantomjs-prebuilt'
29 03 2016 14:12:03.705:WARN [karma]: No captured browser, open http://localhost:9876/
29 03 2016 14:12:03.711:INFO [karma]: Karma v0.13.22 server started at http://localhost:9876/
29 03 2016 14:12:03.714:WARN [launcher]: Can not load "PhantomJS", it is not registered!
  Perhaps you are missing some plugin?
```

**Comment by Healforgreen** [comment] 2016-03-29 21:17
@chovy Have you tried `npm install phantomjs-prebuilt`?

**Comment by chovy** [comment] 2016-03-29 22:09
yes

**Comment by Healforgreen** [comment] 2016-03-30 12:35
I'm using **npm** v2.14.20 and **Node** v4.4.0, and everything is working fine.  Since you are using **nvm**, try installing it with an older version of **Node** instead of the most recent.  It also looks like you're installing it globally?

**Comment by troyblank** [comment] 2016-04-12 03:16
I can also confirm that phantomjs-prebuilt 2.1.7 will give the error:

`Cannot find module 'phantomjs-prebuilt'`

The solution for me was to install phantomjs-prebuilt 2.1.4 as @marlun78 stated.

**Comment by Loonz206** [comment] 2016-04-28 15:34
npm install --save-dev phantomjs-prebuilt worked for me. @Healforgreen I think the spelling was wrong.

**Comment by juliusosokinas** [comment] 2016-04-29 15:46
Same happens with Node.js 6.0.0.

**Comment by jaccus** [comment] 2016-05-13 12:51
Could it be IPv6 localhost related?

**Comment by sshJackofAll** [comment] 2016-05-30 07:40
I am not able to run the app from browser, unable to resolve it.
Not even after installing phantomjs-prebuilt (2.1.7).
node - v4.4.5      npm - 3.9.3 
@jaccus I ran a simple express nodejs app specifying port 3000, and it ran successfully, concluding its not a IPv6 localhost related.

**Comment by joelmukuthu** [comment] 2016-06-05 22:47
I believe this is happening because npm 3 does not automatically install `peerDependencies` anymore. In order for `phantomjs-prebuilt` to be automatically installed as a peer dependency in npm3 (as it works now with npm2) this module needs to list it in its `dependencies` list as well.

**Comment by kemsky** [comment] 2016-06-10 20:59
npm --version
3.8.3
node --version
v5.10.1

    "karma": "^0.13.22",
    "karma-phantomjs-launcher": "^1.0.0",
    "phantomjs-prebuilt": "^2.1.7"

`karma init` creates non-working configuration if you choose phantomjs.

**Comment by andretf** [comment] 2016-06-11 17:23
I was having this issue when I checkout my project on local machine, but on Travis it's ok with this:

    "karma": "^0.13.21",
    "karma-coverage": "^0.5.5",
    "karma-jasmine": "^0.2.2",
    "karma-phantomjs-launcher": "^1.0.0",
    "phantomjs-prebuilt": "^2.1.5"

**I've deleted my `node_modules` and then `npm install` again.**

Then `npm test` magically worked without any issues.
_Sometimes_ it's faster go with a destructive pragmatic approach.
I suggest give this a try if possible..

**Comment by rahil471** [comment] 2016-06-12 08:05
Does not work for me at all.
here is my `package.json`
`"dependencies": {
    "angular": "^1.5.6",
    "jasmine-core": "^2.4.1"
  },
  "devDependencies": {
    "angular-mocks": "^1.5.6",
    "jasmine-core": "^2.4.1",
    "karma": "^0.13.22",
    "karma-jasmine": "^1.0.2",
    "karma-phantomjs-launcher": "^1.0.0",
    "phantomjs": "^2.1.7",
    "phantomjs-prebuilt": "2.1.4"
  }`

npm version - 3.8.6
node version - 6.1.0

**Comment by noherczeg** [comment] 2016-06-15 23:18
Reinstall of node_modules worked for me on Fedora23.

**Comment by noherczeg** [comment] 2016-06-15 23:19
@rahil471 You should not define phantomjs besides phantomjs-prebuilt IMHO.

**Comment by rahil471** [comment] 2016-06-16 14:32
@noherczeg if you see I have already tried that, it's defined just before phantomjs-prebuilt in my package.json

**Comment by noherczeg** [comment] 2016-06-16 14:39
@rahil471 "You should not" :)

**Comment by rahil471** [comment] 2016-06-16 14:40
@noherczeg Opps! Let me try that quickly. Will get Back.

**Comment by rahil471** [comment] 2016-06-16 17:16
I can confirm, even that did not work.

**Comment by paulyoung** [comment] 2016-06-17 17:58
I my case, I needed to add `'karma-phantomjs-launcher'` to the list of `plugins` in `karma.conf.js`:

```
plugins: [
  'karma-phantomjs-launcher',
],
```

**Comment by rahil471** [comment] 2016-06-17 18:01
I managed to get it to work by installing `phantomjs-prebuilt@2.1.4`  and `jasmine-core` globally.

**Comment by taivo** [comment] 2016-06-22 22:14
Like @Loonz206 , it was `npm install --save-dev phantomjs-prebuilt` that did the job for me. Before that I also install phantomjs-prebuilt globally but got the same error. Here is my full list of dependencies in package.json in case it helps others:

```json
"devDependencies": {
    "bower": "^1.7.9",
    "jasmine-core": "^2.4.1",
    "karma": "^0.13.22",
    "karma-jasmine": "^1.0.2",
    "karma-phantomjs-launcher": "^1.0.0",
    "karma-requirejs": "^1.0.0",
    "phantomjs-prebuilt": "^2.1.7",
    "requirejs": "^2.2.0"
  }
```

This was with Node v5.11.1 and npm v3.9.6.

**Comment by CarmenPopoviciu** [comment] 2016-06-23 10:45
what @joelmukuthu said is really the way to go on this. Installing `phantomjs-prebuilt` locally or just adding it as a dep per project will only solve the problem for those of us who do that, and won't fix the core problem of this issue. 

I hope his PR will get merged soon

**Closed** 2016-06-23 16:49 UTC
Labels: support

**Comment by serg94** [comment] 2016-09-05 14:48
'''json
"karma-phantomjs-launcher": "=1.0.0",
"phantomjs": "2.1",
'''
works for me. karma-phantom-launcher 1.0.0 wants phantomjs, not phantomjs-prebuild.

**Comment by rtbm** [comment] 2016-10-04 20:25
Same to me - solved, the question is: are you sure that the karma is running locally with local, not global plugins?
